default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: mini_student_application_test

production:
  <<: *default
  database: mini_student_application_production
  username: mini_student_application
  password: <%= ENV["MINI_STUDENT_APPLICATION_DATABASE_PASSWORD"] %>
